# Generated by Django 4.1.2 on 2022-11-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.PositiveSmallIntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(choices=[('Matemáticas I', 'Matemáticas I'), ('Proyecto de vida\t', 'Proyecto de vida\t'), ('Int informática', 'Introducción a la informática y herramientas'), ('Int ing software', 'Introducción a la ingeniería de software'), ('Programación II', 'Programación II'), ('Lectoescritura', 'Lectoescritura'), ('Matemáticas II', 'Matemáticas II'), ('Teoría del conocimiento', 'Teoría del conocimiento'), ('Pensamiento empr', 'Pensamiento empresarial tendencias de emprendimiento'), ('Metodología de la Investigación', 'Metodología de la Investigación'), ('Diseño web', 'Diseño web')], max_length=50),
        ),
    ]
