# Generated by Django 4.1.2 on 2022-11-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='primerNombre',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='segundoNombre',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre1',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre2',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
