# Generated by Django 4.1.2 on 2022-11-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_nombre1_estudiante_primernombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='primerNombre',
            new_name='nombre1',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='segundoNombre',
            new_name='nombre2',
        ),
    ]
