# Generated by Django 4.1.2 on 2022-11-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_primernombre_estudiante_nombre1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='semestre',
            field=models.PositiveSmallIntegerField(default=True),
            preserve_default=False,
        ),
    ]
